spring:
  application:
    name: dllpoc
  ai:
    azure:
      openai:
        endpoint: https://premi0576824.openai.azure.com/
        api-key: ${AZURE_OPENAI_API_KEY}
        chat:
          deployment-name: gpt-5
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID}
  api:
    key: ${TWILIO_API_KEY}
    secret: ${TWILIO_API_SECRET}
  app:
    sid: ${TWILIO_APP_SID}
cors:
  allowed-headers: ["*"]
  allowed-methods: ["*"]
  allowed-origins: ["*"]

app:
  languages:
    required:
      - nl-BE
      - fr-BE
    selection:
      1:
        en-US: "For English, press 1."
      2:
        nl-NL: "Voor Nederlands, druk op 2."
      3:
        fr-FR: "Pour le français, appuyez sur 3."
      4:
        de-DE: "Für Deutsch drücken Sie 4."
    timeout:
      en-US: "We did not receive your response. Goodbye!"
      nl-NL: "We hebben uw antwoord niet ontvangen. Tot ziens!"
      fr-FR: "Nous n'avons pas reçu votre réponse. Au revoir!"
      de-DE: "Wir haben Ihre Antwort nicht erhalten. Auf Wiedersehen!"