spring:
  application:
    name: dllpoc
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID}
  api:
    key: ${TWILIO_API_KEY}
    secret: ${TWILIO_API_SECRET}
  app:
    sid: ${TWILIO_APP_SID}
cors:
  allowed-headers: ["*"]
  allowed-methods: ["*"]
  allowed-origins: ["*"]